import * as T from 'three';
type Particle={mesh:T.Mesh;velocity:T.Vector3;life:number;max:number};
const material=(color:number,emissive=0)=>new T.MeshStandardMaterial({color,metalness:emissive?0:.55,roughness:emissive?.25:.32,emissive,emissiveIntensity:emissive?1.8:0,transparent:!!emissive,opacity:1,flatShading:true});
export class Effects {
  private holder=new T.Group();private sword=new T.Group();private staff=new T.Group();private particles:Particle[]=[];private swingTime=0;private castTime=0;private recoil=0;private spell=0;private equip=0;private trail:T.Mesh;
  constructor(private scene:T.Scene,private camera:T.Camera){scene.add(camera);camera.add(this.holder);this.holder.position.set(.48,-.52,-.85);this.holder.scale.setScalar(.72);this.holder.add(this.sword,this.staff);
    const grip=material(0x453224),steel=material(0xc9d9da),edge=material(0xe5eef0),gold=material(0xb9a373);
    const add=(parent:T.Group,g:T.BufferGeometry,m:T.Material,x:number,y:number,z:number)=>{let o=new T.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o};
    add(this.sword,new T.CylinderGeometry(.055,.065,.42,7),grip,0,-.38,0);add(this.sword,new T.BoxGeometry(.52,.065,.12),gold,0,-.13,0);add(this.sword,new T.BoxGeometry(.1,.83,.09),steel,0,.32,0);add(this.sword,new T.ConeGeometry(.075,.31,4),edge,0,.89,0);add(this.sword,new T.IcosahedronGeometry(.09,1),material(0x8cc8c6,0x4ba9ad),0,-.12,0);
    add(this.staff,new T.CylinderGeometry(.045,.07,1.65,8),grip,0,0,0);add(this.staff,new T.TorusGeometry(.16,.025,5,24),gold,0,.84,0);let core=add(this.staff,new T.IcosahedronGeometry(.12,1),material(0xa5e8e4,0x58b8cf),0,.84,0);core.userData.core=true;for(let i=0;i<3;i++)add(this.staff,new T.ConeGeometry(.035,.14,5),gold,Math.sin(i*2.1)*.15,.84+Math.cos(i*2.1)*.15,0);
    this.trail=add(this.sword,new T.PlaneGeometry(.08,.95),new T.MeshBasicMaterial({color:0xcceeed,transparent:true,opacity:.0,side:T.DoubleSide,depthWrite:false}),-.12,.35,.06);this.sword.visible=this.staff.visible=false;
  }
  setWeapon(type:'none'|'sword'|'staff'){this.sword.visible=type==='sword';this.staff.visible=type==='staff';this.equip=1;this.holder.position.y=-1.2}
  swordAttack(combo:number,heavy:boolean){this.swingTime=heavy?.58:.35;this.recoil=heavy?.27:.12;this.trail.material=(this.trail.material as T.MeshBasicMaterial).clone();(this.trail.material as T.MeshBasicMaterial).opacity=heavy?.45:.27;this.sword.userData.combo=combo;this.sword.userData.heavy=heavy}
  block(on:boolean){this.sword.userData.block=on}
  cast(spell:number,origin:T.Vector3,direction:T.Vector3,target:T.Vector3){this.castTime=.5;this.recoil=.18;this.spell=spell;let colors=[0xff923f,0xa1e9fa,0xe8e1c9];const burst=(point:T.Vector3,count:number,color:number,spread:number)=>{for(let i=0;i<count;i++){let m=new T.Mesh(new T.IcosahedronGeometry(.03+Math.random()*.065,0),new T.MeshBasicMaterial({color,transparent:true,opacity:.8}));m.position.copy(point);this.scene.add(m);let v=new T.Vector3((Math.random()-.5)*spread,(Math.random()-.2)*spread,(Math.random()-.5)*spread);this.particles.push({mesh:m,velocity:v,life:.5+Math.random()*.5,max:1})}};
    if(spell===0){for(let i=0;i<12;i++){let p=origin.clone().addScaledVector(direction,1+i*.8);burst(p,3,colors[0],2)}burst(target,28,0xffad55,5)}
    else if(spell===1){for(let i=0;i<9;i++){let p=origin.clone().addScaledVector(direction,.7+i*.7);burst(p,5,i%2?0xb9f3ff:0xe2ffff,2.5)}burst(target,18,0xb9f3ff,2)}
    else{for(let i=0;i<4;i++){let ring=new T.Mesh(new T.TorusGeometry(.4+i*.3,.012,4,32),new T.MeshBasicMaterial({color:0xf5f2df,transparent:true,opacity:.24,side:T.DoubleSide}));ring.position.copy(origin).addScaledVector(direction,1+i*1.2);ring.lookAt(origin);this.scene.add(ring);this.particles.push({mesh:ring,velocity:direction.clone().multiplyScalar(4),life:.35,max:.35})}burst(target,26,0xd8d5ba,4)}
  }
  hit(point:T.Vector3,kind:'stone'|'frost'|'fire'='stone'){let color=kind==='frost'?0xcaf6ff:kind==='fire'?0xffa35c:0xc8bbb0;for(let i=0;i<18;i++){let m=new T.Mesh(new T.IcosahedronGeometry(.025+Math.random()*.09,0),new T.MeshBasicMaterial({color,transparent:true,opacity:1}));m.position.copy(point);this.scene.add(m);this.particles.push({mesh:m,velocity:new T.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.35+Math.random()*.7,max:1})}}
  update(dt:number,t:number,moving:number,sprinting:boolean){this.equip=Math.max(0,this.equip-dt*3);this.swingTime=Math.max(0,this.swingTime-dt);this.castTime=Math.max(0,this.castTime-dt);this.recoil=Math.max(0,this.recoil-dt*3);let bob=Math.sin(t*(sprinting?13:9))*moving*(sprinting?.025:.014);this.holder.position.set(.48+Math.cos(t*8)*moving*.01,-.52+bob-this.equip*.6,-.85+this.recoil*.2);this.sword.rotation.set(this.sword.userData.block?-.55:this.swingTime?Math.sin(this.swingTime*13)*(this.sword.userData.heavy?1.2:.8):Math.sin(t*1.3)*.015,this.swingTime?Math.cos(this.swingTime*15)*.65:0,this.sword.userData.block?-.7:this.swingTime?Math.cos(this.swingTime*14)*.9:Math.sin(t*1.5)*.01);this.staff.rotation.z=this.castTime?-.35:Math.sin(t*1.5)*.015;let m=this.trail.material as T.MeshBasicMaterial;m.opacity=Math.max(0,m.opacity-dt*1.5);
    for(let i=this.particles.length-1;i>=0;i--){let p=this.particles[i];p.life-=dt;if(p.life<=0){this.scene.remove(p.mesh);p.mesh.geometry.dispose();(p.mesh.material as T.Material).dispose();this.particles.splice(i,1);continue}p.mesh.position.addScaledVector(p.velocity,dt);p.velocity.y-=dt*2;(p.mesh.material as T.MeshBasicMaterial).opacity=Math.min(.9,p.life/p.max)}
  }
}
